### ISSUE TITLE
README.md usage example uses unknown function

### ISSUE THREAD

**Issue by MalteHillmann** [AaronDMarasco/systemd-watchdog#1]
At first: Thank you for sharing this library!

In file README.md on line 28 you use `wd.enabled()` but i think it should be `wd.is_enabled` ?

Kind regards
Malte Hillmann

**Comment by AaronDMarasco** [comment]
Thanks; good eye. Sorry I just saw this randomly when I was looking at something else. I didn't know you had to "watch" your own projects!

It is a remnant from when I forked from upstream, before I moved it to the more pythonic attribute style. I'll update it today or tomorrow with some better examples I worked up today at work.

**Comment by AaronDMarasco** [comment]
f812506 fleshed it out even more and showed how I was using `socat` to see what would be sent to `systemd`.
